### ISSUE TITLE
Visual Recognition /classify classifier_ids should be array of strings, not string

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/ruby-sdk#20]
Example shows:

```
File.open("./fruitbowl.jpg") do |images_file|
  classes = visual_recognition.classify(
    images_file: images_file,
    threshold: "0.6",
    classifier_ids: "dogsx2018x03x17_1725181949,Connectors_424118776"
  )
```

should be `classifier_ids: ["dogsx2018x03x17_1725181949", "Connectors_424118776"]`

**Comment by mamoonraja** [comment]
Looks like issue has been caused by https://github.com/watson-developer-cloud/ruby-sdk/blob/master/lib/ibm_watson/visual_recognition_v3.rb#L145. Working on changes on the codegen side to fix it.
