### ISSUE TITLE
Unnecessary deprecation warning for 'recognize_using_websocket'

### ISSUE THREAD

**Issue by anweshan** [watson-developer-cloud/ruby-sdk#21]
The code currently gives a deprecation warning for `recognize_using_websocket` 

` Kernel.warn("[DEPRECATION] `recognize_with_websocket` is deprecated and will be removed in the next major release. Please use `recognize_using_websocket` instead.")` in file https://github.com/watson-developer-cloud/ruby-sdk/blob/master/lib/ibm_watson/speech_to_text_v1.rb

This is redundant / confusing

**Comment by mamoonraja** [comment]
We are moving away from `recognize_with_websocket` and the same deprecation warning has been used across all the SDK's.
