### ISSUE TITLE
IAMTokenManager leaks constants names

### ISSUE THREAD

**Issue by lgfa29** [watson-developer-cloud/ruby-sdk#22]
Hi everyone,

I was experiencing some unusual behaviour on a project where, by simply adding the `ibm-watson` gem to the `Gemfile` I would get several requests to fail with a `400 Bad request` error message.

Digging through the code I found out that [IAMTokenManager is declaring constants outside the class scope](https://github.com/watson-developer-cloud/ruby-sdk/blob/master/lib/ibm_watson/iam_token_manager.rb#L8-L14), so they are being leaked to the rest of the application.

This was causing issues for me because [Faraday uses the value of `CONTENT_TYPE` as the header key](https://github.com/lostisland/faraday/blob/master/lib/faraday/request/url_encoded.rb#L3), so my requests were sending a ill-formed ` Application/x-Www-Form-Urlencoded: application/x-www-form-urlencoded` header.

The fix should be simple enough, since I don't think these values are referenced outside this class.

**Comment by mamoonraja** [comment]
Hi @lgfa29 , Thanks a lot for the issue and the PR. We'll review it ASAP.

**Comment by lgfa29** [comment]
Let me know if you need any extra information. I forgot to provide a test case, but this snippet should reproduce the issue:

```rb
require 'logger'
require 'ibm_watson'
require 'faraday'
require 'http_logger'

HttpLogger.logger = Logger.new(STDOUT)
HttpLogger.log_headers = true
HttpLogger.log_request_body  = false
HttpLogger.log_response_body = false

conn = Faraday.new(:url => 'https://reqres.in') do |faraday|
  faraday.request :url_encoded
  faraday.adapter Faraday.default_adapter
end
conn.post('/api/users', { name: "John" })
```

The output will have a wrong header if `ibm_watson` is `require`d. If you comment it out, it won't show.
```
HTTP request header   Application/x-Www-Form-Urlencoded: application/x-www-form-urlencoded
```
