### ISSUE TITLE
List the required dependencies along with their licenses

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/ruby-sdk#26]
| Dependency | License | url |
| --- | --- | --- |
| concurrent-ruby ~> 1.0 | MIT | https://github.com/ruby-concurrency/concurrent-ruby
| eventmachine ~> 1.2 | GPL-2 | https://github.com/eventmachine/eventmachine/blob/master/LICENSE 
| faye-websocket ~> 0.10 | No License ⚠️ | https://github.com/faye/faye-websocket-node/issues/68
| http ~> 3.3 | MIT |
| bundler ~> 1.16 | MIT |
| codecov ~> 0.1 | Apache-2.0 |
| dotenv ~> 2.4 | MIT |
| httplog ~> 1.0 | MIT |
| minitest ~> 5.11 | MIT |
| minitest-hooks ~> 1.5 | MIT |
| minitest-reporters ~> 1.3 | MIT |
| minitest-retry ~> 0.1 | MIT |
| rake ~> 12.3 | MIT |
| rubocop ~> 0.57 | MIT |
| simplecov ~> 0.16 | MIT |
| webmock ~> 3.4 | MIT |

**Comment by germanattanasio** [comment]
@mamoonraja this has been open for a while, would you mind taking a look?

**Comment by germanattanasio** [comment]
It wasn't that hard so I ended up doing it.
