### ISSUE TITLE
Speaker labels unavailable

### ISSUE THREAD

**Issue by yuyaito** [watson-developer-cloud/ruby-sdk#40]
When using real-time recognition using websocket, my application sends below request parameters including "speaker_labels: true," to Watson STT. 
However, my application cannot receive "speaker" (speaker ID) from Watson STT.

```
ws = speech_to_text.recognize_using_websocket(
  recognize_callback: mycallback,
  content_type: "audio/l16;rate=44100",
  chunk_data: true,
  model: 'ja-JP BroadbandModel',
  language_customization_id: nil,
  acoustic_customization_id: nil,
  interim_results: true,
  timestamps: true,
  inactivity_timeout: -1,
  speaker_labels: true,
  profanity_filter: true
)
```

Please research and fix its issue.

**Comment by mamoonraja** [comment]
@yuyaito Thanks for opening the issue, we will investigate and fix the issue.

**Comment by yuyaito** [comment]
Please answer the question about this issue.

Q1. Please tell me the progress for this issue.

Q2. Could you understand the reason of problem?

Q3. When is the release for fix this issue?
       Did you fix this problem in 2019-02-05 release?

**Comment by mamoonraja** [comment]
Hi @yuyaito, We are investigating issues related to STT WebSocket and we are planning to have a patch out by the end of this month, and we are tracking work [here](https://github.com/watson-developer-cloud/ruby-sdk/issues/56).
