### ISSUE TITLE
Cannot Delete Custom Words of Full-Size (Double Byte) Alphanumeric.

### ISSUE THREAD

**Issue by yuyaito** [watson-developer-cloud/ruby-sdk#49]
Ruby-sdk cannot delete custom word of Full-size (double byte) alphanumeric.
I research this issue, and discover to change Full-size alphanumeric to Half-size alphanumeric for normalization.

Base Model: ja-JP_BroadbandModel
Target word example: ＡＢＣ

Please research and fix its issue.

**Comment by germanattanasio** [comment]
Please provide a set of reproducible steps.

**Comment by yuyaito** [comment]
Please answer the question about this issue.

Q1. Please tell me the progress for this issue.

Q2. Could you understand the reason of problem?

Q3. When is the release for fix this issue?

**Comment by mamoonraja** [comment]
Hi, we have an issue and a  PR open to fix the issue in Ruby http library https://github.com/httprb/http/pull/533, we will update the SDK once the PR is merged.
