### ISSUE TITLE
v1 Goals

### ISSUE THREAD

**Issue by mamoonraja** [watson-developer-cloud/ruby-sdk#56]
IBM Watson Ruby SDK is still in beta, We planning to release v1 in September and goal of this issue is to establish timeline add goals for the v1 release.

## Breaking Changes
- [x] Move the core out of the SDK https://github.com/watson-developer-cloud/ruby-sdk/pull/58
- [x] Update all dependencies
- [x] WebSocket Library changes (under investigation), related to https://github.com/faye/faye-websocket-ruby/issues/115
- [x] Disable SSL authentication for Speech Websockets
- [x] https://github.com/watson-developer-cloud/ruby-sdk/issues/49
- [x] #40 
- [x] #50 

---
Would welcome some community feedback on some of these goals - do people want these things? Are there other implementations/packages we should be looking at? Any comments are appreciated!

**Comment by germanattanasio** [comment]
I know we are not pushing a v1.0 but did we fix all the things we said we were going to fix?

**Comment by mamoonraja** [comment]
yep, that's the plan.

**Comment by mamoonraja** [comment]
We decided to keep the SDK in beta for now, and we have moved the core out of SDK and mixed majority of the open issues. Waiting for more info in #50. I will keep an eye on https://github.com/faye/faye-websocket-ruby/issues/115, and the plan is to have it resolved before the major release.

**Comment by mamoonraja** [comment]
The target for the first major release is September 2019.
