### ISSUE TITLE
"language_customization_id" does not work

### ISSUE THREAD

**Issue by nmakino** [watson-developer-cloud/ruby-sdk#69]
**Describe the bug**

"language_customization_id" does not work.

**Additional context**

I found a typo at speech_to_text_v1.rb line 557.

>        "langauge_customization_id" => language_customization_id,

https://github.com/watson-developer-cloud/ruby-sdk/blob/master/lib/ibm_watson/speech_to_text_v1.rb

**Comment by mamoonraja** [comment]
Thanks for opening the issue @nmakino, fix will be out asap.
