### ISSUE TITLE
Unauthorized error for NaturalLanguageUnderstandingV1

### ISSUE THREAD

**Issue by allomov** [watson-developer-cloud/ruby-sdk#75]
**Description**
After using IAM keys (from "Manage" page) and JSON creds (from "Service Credentials" file) I still get `IBMCloudSdkCore::ApiException (Error: Unauthorized, Code: 401, Information: {})` error.

**To Reproduce**

```ruby
iam_api_creds = {
  iam_url: "https://gateway.watsonplatform.net/natural-language-understanding/api",
  iam_apikey: "XXXXXXX",
  version: "2019-07-12"
}

json_service_creds = {
  apikey: "XXXXXXX",
  iam_apikey_description: "Auto-generated for key XXXXXXX",
  iam_apikey_name: "Auto-generated service credentials",
  iam_role_crn: "crn:v1:bluemix:public:iam::::serviceRole:Manager",
  iam_serviceid_crn: "crn:v1:bluemix:public:iam-identity::a/XXXXXXX::serviceid:ServiceId-XXXXXXX-51d4-429e-95b1-XXXXXXX",
  url: "https://gateway.watsonplatform.net/natural-language-understanding/api"
}

natural_language_understanding = IBMWatson::NaturalLanguageUnderstandingV1.new(iam_api_creds)

response = natural_language_understanding.analyze(
  text: "Bruce Banner is the Hulk and Bruce Wayne is BATMAN!", features: { "entities" => {} }
).result # Getting IBMCloudSdkCore::ApiException#Unauthorized exception here

natural_language_understanding = IBMWatson::NaturalLanguageUnderstandingV1.new(json_service_creds)

response = natural_language_understanding.analyze(
  text: "Bruce Banner is the Hulk and Bruce Wayne is BATMAN!", features: { "entities" => {} }
).result # Getting IBMCloudSdkCore::ApiException#Unauthorized exception here
```

**Expected behavior**
Result of NLP processing.

**Actual behavior**
Getting following error
```
IBMCloudSdkCore::ApiException (Error: Unauthorized, Code: 401, Information: {})
```

**Desktop (please complete the following information):**
 - Mac OS X 10.13.6
 - Ruby 2.5.1
 - I've tried with 0.12.0, 0.17.1 and 0.19.1 watson-developer-cloud/ruby-sdk versions

**Additional context**
Approximately half of a year I got this running with version 0.12

**Comment by mamoonraja** [comment]
Hi @allomov, thanks a lot for opening the issue. One problem I see in `iam_api_creds` is that you are using the service URL as `iam_url`. Try using:

```
iam_api_creds = {
  version: "2018-03-16",
  iam_apikey: "<iam_api_key>",
  iam_url: "https://iam.cloud.ibm.com/identity/token", // default iam url
  url: "https://gateway.watsonplatform.net/natural-language-understanding/api"
}
```

Please check out the documentation for providing iam API keys [here](https://github.com/watson-developer-cloud/ruby-sdk#supplying-the-iam-api-key). The problem with `json_service_creds` is that `version` date is not provided.

**Comment by allomov** [comment]
Thank you very much for such quick response. That helped me a lot. And saved my day finally.

I needed to do following changes to the service json to make it work:
- rename `apikey` to `iam_apikey`
- add version field (`version: "2019-07-12"`)

**Comment by mamoonraja** [comment]
You are welcome! Please feel free to report any issues or leave feedback in #56 as we are planning to do a major release in September.

**Comment by allomov** [comment]
At the moment I don’t have any problems with it. Wish you to have a good release :)
