### ISSUE TITLE
Returns LoadError (cannot load such file -- ibm_watson/authenticators):

### ISSUE THREAD

**Issue by drwhirst** [watson-developer-cloud/ruby-sdk#85]
I am trying to test out watson NLU features, and I keep getting this error:

```
LoadError (cannot load such file -- ibm_watson/authenticators):
  
app/controllers/concerns/watson.rb:2:in `<module:Watson>'
app/controllers/concerns/watson.rb:1:in `<main>'
app/controllers/messages_controller.rb:2:in `<class:MessagesController>'
app/controllers/messages_controller.rb:1:in `<main>'
Started POST "/messages" for ::1 at 2020-01-16 14:57:36 -0500
```

My ruby version is 2.6.2 and I am running on Rails 6.0.1

Please help

the code is as follows: 

```
require "ibm_watson/authenticators"
    require "ibm_watson/natural_language_understanding_v1"
    include IBMWatson

    def parse_messages()
        authenticator = IBMWatson::Authenticators::IamAuthenticator.new(
            apikey: ENV['API_KEY'],
        )
         
        natural_language_understanding = NaturalLanguageUnderstandingV1.new(
            version: "2019-07-12",
            authenticator: authenticator
        )
        natural_language_understanding.service_url = ENV['API_URL']
        response = natural_language_understanding.analyze(
            url: "www.ibm.com",
            features: {categories: {limit:3}}
        )
        puts JSON.pretty_generate(response.result)
    end
```

**Comment by mamoonraja** [comment]
Hi @drwhirst , Thanks for opening the issue, can you please confirm which version of Ruby SDK are you using?

**Comment by drwhirst** [comment]
ibm_watson-0.20.1

**Comment by drwhirst** [comment]
I resolved this issue by switching my ruby  version from 2.6.2 to 2.6.0, as 2.6.2 isn't supported by the gem

**Comment by rafaltrojanowski** [comment]
Same issue with ruby 2.6.3p62. Thanks for sharing @drwhirst

**Comment by ajshemi** [comment]
I wonder if a solution has been found for this load error issue

**Comment by mamoonraja** [comment]
I see an issue on [rails repo](https://github.com/rails/rails/issues/37464), It looks like the fix is to move to `6.0.x` stable version. Which version are you using @ajshemi ?

**Comment by ajshemi** [comment]
I am ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin17]. is the version acceptable?

**Comment by ajshemi** [comment]
It worked. I think I was missing the right apikey. 

ruby version
ruby -v
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin17]

my gemfile includes
ruby '2.6.1'
gem 'ibm_watson', '~> 1.3

**Comment by rafaltrojanowski** [comment]
I can say that when I added it to Gemfile in that way:

```
gem 'ibm_watson'
```

it installed a version where authenticator was missing in the codebase, so that was the reason for the error from the title.

Not sure how many Rails devs would use it but IMHO it would be good to add docs for installation with Rails, like:

```
gem 'ibm_watson', '~> 1.3
```

Btw, thanks for a great gem!

**Comment by mamoonraja** [comment]
@ajshemi Glad, it worked :)

Thanks, @rafaltrojanowski, Interesting why `rails` is not adding the recent version. We will look into adding additional instructions for people seeing this issue in `rails`. One additional issue with adding a specific version in the readme is that semantic release has to update `readme` too. Anyways we will update the instructions soon :)

**Comment by Mikemosca** [comment]
talked with @mamoonraja and will we close this one for now.
